---
label: global settings
hide_body: true
fields:
- name: hero
  type: field_group
  config: {}
  fields:
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Title
  label: Hero section
- name: a-propos
  type: field_group
  config: {}
  fields:
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Text
  label: A propos
- name: decouvrir
  type: field_group
  config: {}
  fields:
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Text
  - name: cta
    type: text
    config:
      required: false
    label: Call To action
  label: DÃ©couvrir
- name: footer
  type: field_group
  config: {}
  fields:
  - name: text
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Text
  - name: address
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: true
      schema:
        format: html-blocks
    label: Adresse
  label: Footer
pages:
- _data/params.json
